import { Vehicle, UserPreferences, ScenarioPreset, RegisteredUsedCar } from '@/types/vehicle';

export const DEFAULT_USED_CAR: RegisteredUsedCar = {
  brand: 'Honda',
  model: 'HR-V',
  version: 'EX 1.8 Automático',
  yearModel: 2019,
  fipeValue: 98707.00,
  lengthMm: 4294,
  widthMm: 1772,
  wheelbaseMm: 2610,
  weightKg: 1270,
  trunkVolumeLiters: 437,
  zeroToHundredSeconds: 11.2,
  powerHp: 140,
  torqueKgfm: 17.5,
  totalRangeKm: 560,
  airbagsCount: 4,
  urbanGasolineKmL: 11.0,
  highwayGasolineKmL: 12.3,
  tco3Years: 38500.00,
  fipeLastUpdated: 'Outubro/2026 (Atualizada)',
};

export const INITIAL_PREFERENCES: UserPreferences = {
  isofixMinDistanceCm: 45,
  maxStorePrice: 200000, // Desclassifica acima de R$ 200.000,00
  maxLengthMm: 4500, // Desclassifica muito acima de 4500 mm
  autoEliminateIncompatible: true,
  excludeBEV: false,
  
  annualKm: 15000,
  urbanSharePercent: 75,
  gasolinePricePerLiter: 6.20,
  ethanolPricePerLiter: 4.10,
  electricityPricePerKwh: 0.95,
  selectedState: 'BA',
  ipvaRatePercent: 2.5, // Alíquota oficial Bahia: 2,5%
  tcoYearsPeriod: 3, // TCO de 3 anos
  
  usedCar: DEFAULT_USED_CAR,
  
  weights: {
    familySpace: 30,
    tco: 20,
    safety: 15,
    powertrainEfficiency: 10,
    comfort: 10,
    warrantyResale: 10,
    technology: 5,
  },
};

export const SCENARIO_PRESETS: ScenarioPreset[] = [
  {
    id: 'padrao_familiar',
    name: 'Padrão Familiar Salvador / RMS (15.000 km/ano)',
    description: 'Rotina urbana com escola, compras e viagens ao Litoral Norte.',
    annualKm: 15000,
    urbanSharePercent: 75,
    gasolinePrice: 6.20,
    electricityPrice: 0.95,
  },
  {
    id: 'uso_intenso',
    name: 'Uso Intenso Bahia (25.000 km/ano)',
    description: 'Deslocamento intermunicipal frequente (ex: Salvador - Feira).',
    annualKm: 25000,
    urbanSharePercent: 60,
    gasolinePrice: 6.20,
    electricityPrice: 0.95,
  },
  {
    id: 'energia_solar',
    name: 'Energia Solar Fotovoltaica (R$ 0,20 / kWh)',
    description: 'Recarga residencial com geração própria quase gratuita.',
    annualKm: 15000,
    urbanSharePercent: 80,
    gasolinePrice: 6.20,
    electricityPrice: 0.20,
  },
];

export const INITIAL_VEHICLES: Vehicle[] = [
  {
    id: 'byd-song-plus-2025',
    brand: 'BYD',
    model: 'Song Plus',
    version: 'DM-i 18.3 kWh',
    powertrain: 'PHEV',
    status: 'Finalista',
    yearManufacture: 2024,
    yearModel: 2025,
    dealership: 'BYD Parvi Salvador',
    sellerName: 'Rodrigo Santana',
    notes: 'Excelente acabamento e espaço interno. Fita métrica medida no test-drive: 46.5 cm entre pontos ISOFIX internos.',
    financial: {
      tablePrice: 239800.00,
      storePrice: 234800.00,
      usedCarEvaluation: 78000.00,
      paymentConditions: [
        {
          id: 'cond-1',
          name: 'Entrada 50% + 24x Taxa Zero',
          downPayment: 117400.00,
          useUsedCarAsDownPayment: true,
          financedAmount: 39400.00,
          months: 24,
          mode: 'RATE_TO_INSTALLMENT',
          monthlyRatePercent: 0.0,
          installmentValue: 1641.67,
          totalPaid: 234800.00,
          totalInterest: 0.0,
        },
      ],
    },
    familySpace: {
      isofixDistanceCm: 46.5,
      passengerCapacity: 5,
      lengthMm: 4705,
      widthMm: 1890,
      wheelbaseMm: 2765,
      weightKg: 1700,
    },
    trunk: {
      volumeLiters: 574,
      spareTireKit: 'Kit reparo',
      electricTailgate: true,
    },
    powertrainSpec: {
      totalPowerHp: 235,
      torqueKgfm: 40.8,
      zeroToHundredSeconds: 7.9,
      totalRangeKm: 1100,
      drivetrain: 'FWD',
      batteryKwh: 18.3,
      electricRangeKm: 105,
    },
    consumption: {
      urbanKmL: 15.1,
      highwayKmL: 13.2,
    },
    safety: {
      airbagsCount: 6,
      hasAdas: true,
      hasBlindSpotAlert: true,
      hasCamera360: true,
    },
    warrantyCosts: {
      generalWarrantyYears: 6,
      batteryWarrantyYears: 8,
      ipvaAnnual: 5870.00, // 2.5% de R$ 234.800
      insuranceAnnual: 5900.00,
      revisions3Years: 3450.00,
      consumption3Years: 11200.00,
    },
    comfortTech: {
      electricSeats: true,
      rearAirVents: true,
      carPlayWireless: true,
      panoramicSunroof: true,
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'gwm-haval-h6-hev',
    brand: 'GWM',
    model: 'Haval H6',
    version: 'HEV2',
    powertrain: 'HEV',
    status: 'Visitei',
    yearManufacture: 2024,
    yearModel: 2025,
    dealership: 'GWM Morena Salvador',
    sellerName: 'Carla Silveira',
    notes: 'Ótima resposta de motor, suspensão calibrada para piso brasileiro. Medição de ISOFIX a ser realizada.',
    financial: {
      tablePrice: 216000.00,
      storePrice: 214000.00,
      usedCarEvaluation: 76000.00,
      paymentConditions: [
        {
          id: 'cond-1',
          name: 'Entrada 60% + 36x CDC',
          downPayment: 128400.00,
          useUsedCarAsDownPayment: true,
          financedAmount: 52400.00,
          months: 36,
          mode: 'RATE_TO_INSTALLMENT',
          monthlyRatePercent: 0.99,
          installmentValue: 1735.20,
          totalPaid: 243267.20,
          totalInterest: 10067.20,
        },
      ],
    },
    familySpace: {
      isofixDistanceCm: null, // Pendente de medição na loja!
      passengerCapacity: 5,
      lengthMm: 4683,
      widthMm: 1886,
      wheelbaseMm: 2738,
      weightKg: 1699,
    },
    trunk: {
      volumeLiters: 560,
      spareTireKit: 'Estepe temporário',
      electricTailgate: true,
    },
    powertrainSpec: {
      totalPowerHp: 243,
      torqueKgfm: 54.0,
      zeroToHundredSeconds: 7.9,
      totalRangeKm: 980,
      drivetrain: 'FWD',
      batteryKwh: 1.6,
      electricRangeKm: 0,
    },
    consumption: {
      urbanKmL: 13.8,
      highwayKmL: 12.0,
    },
    safety: {
      airbagsCount: 6,
      hasAdas: true,
      hasBlindSpotAlert: true,
      hasCamera360: true,
    },
    warrantyCosts: {
      generalWarrantyYears: 5,
      batteryWarrantyYears: 8,
      ipvaAnnual: 5350.00, // 2.5% de R$ 214.000
      insuranceAnnual: 5400.00,
      revisions3Years: 3200.00,
      consumption3Years: 13900.00,
    },
    comfortTech: {
      electricSeats: true,
      rearAirVents: true,
      carPlayWireless: true,
      panoramicSunroof: true,
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'toyota-corolla-cross-hybrid',
    brand: 'Toyota',
    model: 'Corolla Cross',
    version: 'XRX Hybrid',
    powertrain: 'HEV',
    status: 'Aguardando proposta',
    yearManufacture: 2024,
    yearModel: 2025,
    dealership: 'Toyota Guebor Salvador',
    sellerName: 'Marcos Vinicius',
    notes: 'Confiabilidade e liquidez lendárias. Distância ISOFIX menor.',
    financial: {
      tablePrice: 213000.00,
      storePrice: 209900.00,
      usedCarEvaluation: 82000.00,
      paymentConditions: [],
    },
    familySpace: {
      isofixDistanceCm: 42.0, // menor que 45cm -> descartado pelo critério familiar
      passengerCapacity: 5,
      lengthMm: 4460,
      widthMm: 1825,
      wheelbaseMm: 2640,
      weightKg: 1450,
    },
    trunk: {
      volumeLiters: 440,
      spareTireKit: 'Estepe temporário',
      electricTailgate: true,
    },
    powertrainSpec: {
      totalPowerHp: 122,
      torqueKgfm: 16.6,
      zeroToHundredSeconds: 13.0,
      totalRangeKm: 820,
      drivetrain: 'FWD',
      batteryKwh: 1.3,
      electricRangeKm: 0,
    },
    consumption: {
      urbanKmL: 17.8,
      highwayKmL: 14.7,
    },
    safety: {
      airbagsCount: 7,
      hasAdas: true,
      hasBlindSpotAlert: true,
      hasCamera360: false,
    },
    warrantyCosts: {
      generalWarrantyYears: 5,
      batteryWarrantyYears: 8,
      ipvaAnnual: 5247.50, // 2.5% de R$ 209.900
      insuranceAnnual: 4600.00,
      revisions3Years: 2980.00,
      consumption3Years: 10800.00,
    },
    comfortTech: {
      electricSeats: true,
      rearAirVents: true,
      carPlayWireless: true,
      panoramicSunroof: true,
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'caoa-chery-tiggo-7-pro-hybrid',
    brand: 'Caoa Chery',
    model: 'Tiggo 7 Pro',
    version: 'Hybrid Max Drive 48V',
    powertrain: 'HEV',
    status: 'Finalista',
    yearManufacture: 2024,
    yearModel: 2025,
    dealership: 'D21 Motors Salvador (Bonocô)',
    sellerName: 'Leandro Pires',
    notes: 'Dentro do teto de preço (R$ 169.990) e comprimento de 4.500 mm. Medição ISOFIX presencial: 45,5 cm comprovados.',
    financial: {
      tablePrice: 179990.00,
      storePrice: 169990.00,
      usedCarEvaluation: 80000.00,
      paymentConditions: [],
    },
    familySpace: {
      isofixDistanceCm: 45.5, // >= 45 cm (atende plenamente)
      passengerCapacity: 5,
      lengthMm: 4500, // <= 4500 mm (dentro do limite)
      widthMm: 1842,
      wheelbaseMm: 2670,
      weightKg: 1475,
    },
    trunk: {
      volumeLiters: 475,
      spareTireKit: 'Estepe temporário',
      electricTailgate: true,
    },
    powertrainSpec: {
      totalPowerHp: 160,
      torqueKgfm: 25.5,
      zeroToHundredSeconds: 9.7,
      totalRangeKm: 740,
      drivetrain: 'FWD',
      batteryKwh: 0.9,
      electricRangeKm: 0,
    },
    consumption: {
      urbanKmL: 11.6,
      highwayKmL: 11.4,
    },
    safety: {
      airbagsCount: 6,
      hasAdas: true,
      hasBlindSpotAlert: true,
      hasCamera360: true,
    },
    warrantyCosts: {
      generalWarrantyYears: 5,
      batteryWarrantyYears: 5,
      ipvaAnnual: 4249.75, // 2.5% de R$ 169.990
      insuranceAnnual: 4200.00,
      revisions3Years: 2850.00,
      consumption3Years: 13500.00,
    },
    comfortTech: {
      electricSeats: true,
      rearAirVents: true,
      carPlayWireless: true,
      panoramicSunroof: true,
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
